### ISSUE TITLE
Plugin only works on install, crash if sublime is relaunched

### ISSUE THREAD

**Issue by akabab** [coronalabs/CoronaSDK-SublimeText#41]
When I install the plugin, everything works fine.
If sublime is relaunched, completions doesn't work anymore, and probably other stuffs. This is what the console says:

```
reloading plugin Corona Editor._corona_utils
reloading plugin Corona Editor._lua_paths
reloading plugin Corona Editor._sublime_utils
reloading plugin Corona Editor.about
reloading plugin Corona Editor.completions
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/akabab/Library/Application Support/Sublime Text 3/Installed Packages/Corona Editor.sublime-package/completions.py", line 27, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'User/CoronaSDKLua.sublime-settings'
reloading plugin Corona Editor.corona_docs
reloading plugin Corona Editor.debugger
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/akabab/Library/Application Support/Sublime Text 3/Installed Packages/Corona Editor.sublime-package/debugger.py", line 20, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'User/CoronaSDKLua.sublime-settings'
reloading plugin Corona Editor.run_project
reloading plugin Corona Editor.snippets
Traceback (most recent call last):
  File "/Users/akabab/Library/Application Support/Sublime Text 3/Installed Packages/Corona Editor.sublime-package/snippets.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/akabab/Library/Application Support/Sublime Text 3/Installed Packages/Corona Editor.sublime-package/completions.py", line 27, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'User/CoronaSDKLua.sublime-settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/akabab/Library/Application Support/Sublime Text 3/Installed Packages/Corona Editor.sublime-package/snippets.py", line 21, in <module>
ImportError: No module named 'completions'
```

Any idea? 
Thx u

**Comment by Shchvova** [comment]
@personalnadir may I ask you to give a hand here?

**Comment by personalnadir** [comment]
I'm a bit confused. The only direct reference to the missing file is in the debugger.py. The line numbers themselves point to comments, so it's hard to say what's causing them.

**Comment by akabab** [comment]
@Shchvova @personalnadir thanks both for your concern. Tell me if I can give you more informations

**Comment by akabab** [comment]
This error `No such file or directory: 'User/CoronaSDKLua.sublime-settings'` intrigates me, the file do exists actually..

**Comment by akabab** [comment]
#42 did the trick indeed
